---
#- hosts: localhost
#  connection: local
#  roles:
#    - local

#  tasks:
#  - add_host:
#      name: "{{ dbs_hostname }}"
#      groups: working_group
#    changed_when: false
#    tags:
#      - always

# - hosts: working_group
- hosts: nodes
  gather_facts: False
  become: true

  roles:
    - common
    - k8s
