---
- name: cluster_services | Capturing K8s Services
  command: >
    kubectl get services --all-namespaces -o json
  changed_when: false
  become: false
  tags:
    - k8s_get_dashboard
  register: _k8s_get_services_all
  when: k8s_reports['all_service_namespaces']|bool

- name: cluster_services | Displaying K8s Services
#  debug:
#    var: (_k8s_get_services_all['stdout']|from_json)['items']
  debug:
    msg: "{{ lookup('template', 'k8s_services.j2') }}"
  when: k8s_reports['all_service_namespaces']|bool

