---
# We look for this currently just as a check to ensure cluster has been
# initialized or not. This should probably change.
- name: init_cluster | Checking If Cluster Is Already Initialized
  stat:
    path: "{{ k8s_admin_config }}"
  tags:
    - k8s_get_dashboard
  register: _k8s_kubectl_cluster_info
  delegate_to: "{{ k8s_master }}"

- name: init_cluster | Setting State Of Cluster
  set_fact:
    k8s_cluster_init: "{{ _k8s_kubectl_cluster_info['stat']['exists'] }}"
  tags:
    - k8s_get_dashboard

# - name: init_cluster | Showing Status1 Of Cluster Fact
#   debug: 
#     var: _k8s_kubectl_cluster_info

# - name: init_cluster | Showing Status Of Cluster Fact
#   debug: msg="Cluster already initialized == {{ k8s_cluster_init }}"

- name: init_cluster | Initializing Cluster Master
  command: >
           kubeadm init \
           --pod-network-cidr 10.244.0.0/16 \
           --apiserver-advertise-address \
           {{ hostvars[inventory_hostname]['k8s_advertise_address'] }} \
           --apiserver-bind-port \
           {{ k8s_advertise_bind_port }}
#           --token {{ k8s_token }}
  register: _k8s_cluster_master_init
  become: true
#  no_log: true
  when: >
        (inventory_hostname == k8s_master) and
        not k8s_cluster_init

- name: init_cluster | Create directory .kube if it does not exist
  file:
    path: ~/.kube
    state: directory
    mode: '0755'
  become: false
  when: inventory_hostname == k8s_master

- name: init_cluster | Create directory .kube in localhost if it does not exist
  file:
    path: ~/.kube
    state: directory
    mode: '0755'
  become: false
  delegate_to: localhost
  when: inventory_hostname == k8s_master

- name: init_cluster | Check whether /home/pirate/.kube/config already exists
  stat:
    path: /home/pirate/.kube/config
  register: st
  when: inventory_hostname == k8s_master

# - name: init_cluster | Showing State Of /home/pirate/.kube/config
#   debug: msg="file /home/pirate/.kube/config == {{ st }}"

- name: init_cluster | Copy /etc/kubernetes/admin.conf /home/pirate/.kube/config
  command: cp /etc/kubernetes/admin.conf /home/pirate/.kube/config
  become: true
  when: >
         (inventory_hostname == k8s_master) and
         st.stat.exists == False

- name: init_cluster | set access rights of /home/pirate/.kube/config
  file:
    path: /home/pirate/.kube/config
    owner: pirate
    group: pirate
    mode: '0600'
  become: true
  when: inventory_hostname == k8s_master

- name: init_cluster | fetch /home/pirate/.kube/config to ~/.kube/config
  fetch:
    src: /home/pirate/.kube/config
    dest: ~/.kube/config
    flat: yes
  become: false
  when: inventory_hostname == k8s_master

- name: init_cluster | Get Token
  shell: "kubeadm token list | awk '{print $1}' | tail -1"
  register: _k8s_token
  become: true
  changed_when: false
#  no_log: true
  delegate_to: "{{ k8s_master }}"

- name: init_cluster | Show old token
  debug:
    var: _k8s_token
  become: false

- name: init_cluster | Setting Token 1
  set_fact:
    k8s_token: "{{ _k8s_token['stdout_lines'][0] }}"
#  no_log: true
  when: (_k8s_token['stdout_lines'][0] != 'TOKEN')

- name: init_cluster | create Token
  command: kubeadm token create
  register: _k8s_token
  become: true
  changed_when: false
#  no_log: true
  delegate_to: "{{ k8s_master }}"
  when: ((_k8s_token['stdout_lines'][0] == 'TOKEN') or (_k8s_token['stdout_lines'][0] == '' ))

#- name: init_cluster | Show new token
#  debug:
#    var: _k8s_token

- name: init_cluster | Setting Token 2
  set_fact:
    k8s_token: "{{ _k8s_token['stdout_lines'][0] }}"
#  no_log: true
  when: (_k8s_token.changed == True)

# - name: init_cluster | Saving Token On Master
#   template:
#     src: k8s_token.j2
#     dest: "{{ k8s_token_file }}"
#     owner: root
#     group: root
#     mode: u=rw,g=r,o=
#   become: true
#   when: >
#         (inventory_hostname == k8s_master) and
#         not k8s_cluster_init

