---
- name: join_cluster | show vars
  debug: msg="hostvars == {{ k8s_advertise_address }}:{{ k8s_advertise_bind_port }}"

- name: join_cluster | Joining Additional Nodes To K8s Cluster
  command: >
           kubeadm join \
           {{ k8s_advertise_address }}:{{ k8s_advertise_bind_port }} \
           --token {{ k8s_token }} \
           --discovery-token-unsafe-skip-ca-verification \
           --ignore-preflight-errors=SystemVerification
  args:
    creates: /etc/kubernetes/kubelet.conf
  become: true
#  no_log: true
  when: >
        k8s_cluster_init and
        k8s_cluster_init_skip_ca_verification

- name: join_cluster | Joining Additional Nodes To K8s Cluster
  command: >
           kubeadm join \
           --token {{ k8s_token }} \
           {{ k8s_advertise_address }}:{{ k8s_advertise_bind_port }}
  args:
    creates: /etc/kubernetes/kubelet.conf
  become: true
#  no_log: true
  when: >
        k8s_cluster_init and
        not k8s_cluster_init_skip_ca_verification

